### ISSUE TITLE
File "/usr/src/app/Evil-Twin-tool-master/tool.py", line 121     p = subprocess.Popen(command, stdout=subprocess.PIPE)

### ISSUE THREAD

**Issue by gabriele-costa** [vection/Evil-Twin-tool#1]
Hi, I am getting this error when running ```python tool.py```

```
File "/usr/src/app/Evil-Twin-tool-master/tool.py", line 121
    p = subprocess.Popen(command, stdout=subprocess.PIPE)
```
I am running the project under the official python 3 docker container (python:3).
Checking line 121 in the source code, it seems that a mix of spaces and tabs has been used. Perhaps this is this is the reason behind the error.

**Comment by gabriele-costa** [comment]
Manually fixing this in the source code leads to another, similar error at line 122 (```else``` statement). Perhaps this is a more general issue.

**Comment by vection** [comment]
I used python2.7 to run it so you might need to change to python 3
Anyway, you can fix it and pull request this. I'm not willing to work on it anymore sorry.
